/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExternalAccountWithVerificationVerification {
    Oauth(Box<models::Oauth>),
    GoogleOneTap(Box<models::GoogleOneTap>),
    Simple(Box<SimpleVerification>),
}

impl Default for ExternalAccountWithVerificationVerification {
    fn default() -> Self {
        Self::Oauth(Default::default())
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimpleVerification {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "strategy")]
    pub strategy: Strategy,
    #[serde(rename = "attempts")]
    pub attempts: Option<i32>,
    #[serde(rename = "expire_at")]
    pub expire_at: i64,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "unverified")]
    Unverified,
    #[serde(rename = "verified")]
    Verified,
}

impl Default for Status {
    fn default() -> Status {
        Self::Unverified
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Strategy {
    #[serde(rename = "google_one_tap")]
    GoogleOneTap,
    #[serde(rename = "oauth_google")]
    OauthGoogle,
    #[serde(rename = "oauth_facebook")]
    OauthFacebook,
    #[serde(rename = "oauth_github")]
    OauthGithub,
    #[serde(rename = "oauth_gitlab")]
    OauthGitlab,
    #[serde(rename = "oauth_discord")]
    OauthDiscord,
    #[serde(rename = "oauth_twitch")]
    OauthTwitch,
    #[serde(rename = "oauth_linkedin")]
    OauthLinkedin,
    #[serde(rename = "oauth_twitter")]
    OauthTwitter,
    #[serde(rename = "oauth_microsoft")]
    OauthMicrosoft,
    #[serde(rename = "oauth_hubspot")]
    OauthHubspot,
    #[serde(rename = "oauth_dropbox")]
    OauthDropbox,
    #[serde(rename = "oauth_tiktok")]
    OauthTiktok,
    #[serde(rename = "oauth_slack")]
    OauthSlack,
    #[serde(rename = "oauth_notion")]
    OauthNotion,
}

impl Default for Strategy {
    fn default() -> Strategy {
        Self::GoogleOneTap
    }
}
