/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSettingsPeriodAttackProtectionSettings {
    #[serde(rename = "user_lockout")]
    pub user_lockout: Box<models::UserSettingsPeriodAttackProtectionSettingsPeriodUserLockout>,
    #[serde(rename = "pii")]
    pub pii: Box<models::UserSettingsPeriodAttackProtectionSettingsPeriodPii>,
    #[serde(rename = "email_link")]
    pub email_link: Box<models::UserSettingsPeriodAttackProtectionSettingsPeriodEmailLink>,
}

impl UserSettingsPeriodAttackProtectionSettings {
    pub fn new(
        user_lockout: models::UserSettingsPeriodAttackProtectionSettingsPeriodUserLockout,
        pii: models::UserSettingsPeriodAttackProtectionSettingsPeriodPii,
        email_link: models::UserSettingsPeriodAttackProtectionSettingsPeriodEmailLink,
    ) -> UserSettingsPeriodAttackProtectionSettings {
        UserSettingsPeriodAttackProtectionSettings {
            user_lockout: Box::new(user_lockout),
            pii: Box::new(pii),
            email_link: Box::new(email_link),
        }
    }
}
