name: Checks

on:
  push:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt

    - name: rust cache
      uses: Swatinem/rust-cache@v2 
    
    - name: Check formatting
      run: cargo fmt --check
      
    - name: Check compilation
      run: cargo check
      
    - name: Run tests
      run: cargo test 